### ISSUE TITLE
部署

### ISSUE THREAD

**Issue by tamako-1** [MikuNyanya/RabbitBot_RE#2]
大佬 ，项目该如何部署呀，纯萌新\(//∇//)\

**Comment by MikuNyanya** [comment]
由于至今为止都是自用的机器人，没有考虑过其他人部署的问题
先配置rabbitbot_re.properties
然后maven打包
最后运行jar包

部署问题虽然已经在计划了，但是工作忙，而且我懒，正处于薛定谔的鸽了状态

**Comment by tamako-1** [comment]
感谢回复！我试试
