### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Qi33D88** [MikuNyanya/RabbitBot_RE#3]
`WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rabbitBot': Unsatisfied dependency expressed through field 'nudgeEvents'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nudgeEvents': Unsatisfied dependency expressed through field 'nudgeService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nudgeService': Unsatisfied dependency expressed through field 'botAccount'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "è´¦å·"
12:10:34 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener -

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
12:10:34 [main] ERROR org.springframework.boot.SpringApplication - Application run 

> 

> failed`

**Comment by MikuNyanya** [comment]
see [here](https://github.com/MikuNyanya/RabbitBot_RE/blob/master/Releases.md)
