### ISSUE TITLE
请问爆红怎么处理

### ISSUE THREAD

**Issue by hyopjy** [MikuNyanya/RabbitBot_RE#8]
<img width="1338" alt="image" src="https://github.com/MikuNyanya/RabbitBot_RE/assets/49136692/274da913-5ad6-453c-a5eb-ebe0dd6b9f0f">

**Comment by hyopjy** [comment]
jar包可以下载 但是 会爆红 引用不到

**Comment by MikuNyanya** [comment]
从图上看，是因为没加载到mirai的包，但既然你说包能下载
那首先确认idea版本是2021以上的，旧版本idea有类似的bug
如果idea没问题，请排查maven以及pom
单一张图我看不出问题根源，但可以肯定是本地引用问题而非代码问题

**Comment by hyopjy** [comment]
好的。谢谢
